spring:
  application:
    name: persome

  datasource:
    url: jdbc:mysql://localhost:3306/persome?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false

  config:
    import: "optional:classpath:application-secret.yml"

server:
  port: 8080
